version: '2'
services:
  wordpress:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
    ports:
      - 8888:80
    networks:
      - myNetwork
    volumes:
      - ./:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
  db:
    env_file:
      .env
    image: mariadb
    restart: always
    volumes:
      - ./.database:/var/lib/mysql    
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    networks:
      myNetwork:
        ipv4_address: 172.29.0.2
  phpmyadmin:
    env_file:
      .env
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      UPLOAD_LIMIT: 25M
    networks:
      - myNetwork
  compass:
    image: dedavidson/compass-watch
    command: watch --poll /src/compass
    volumes:
      - ./:/src
      - ../wp-content/themes/${THEME_NAME}:/dest
networks:
  myNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
          gateway: 172.29.0.1
volumes:
  database:
